### ISSUE TITLE
Set classes on list item

### ISSUE THREAD

**Issue by spdawson** [tscanlin/tocbot#12]
Alongside the
```
  listClass: 'toc-list'
```
configuration option for the `ul` list elements, it would be very useful to also have an option for applying class(es) to the `li` list item elements. Something like
```
listItemClass: 'toc-list-item'
```
For example, this would make it possible to use a Bootstrap list group for the TOC, by applying the `list-group` class at `ul` level, and the `list-group-item` class at `li` level.

**Comment by tscanlin** [comment]
Couldn't you use the 'extraLinkClasses' option and just style the links rather than the list items? If that doesn't work for you then I'd be open to adding this option. Would you be interested in implementing this and opening a pull request? If not let me know and I can try to get to it later this weekend.

Thanks for checking this project out and making the suggestion!

**Comment by spdawson** [comment]
Unfortunately, for my use case (Bootstrap list groups) it is necessary to add the extra class at the list item level --- adding the class on the link element does not work. PR #13 opened.

**Comment by tscanlin** [comment]
Thank you! I've released a new version with your PR.
