### ISSUE TITLE
Simultaneous scrolling and collapsing

### ISSUE THREAD

**Issue by cucumberry** [tscanlin/tocbot#131]
When you use the TOC to jump around, these things clearly happen sequentially:

1. Scrolling
2. Destination section expands (if applicable)
3. Origin section collapses (if applicable)

The delay that causes is a bit annoying when you know you want to jump to a subsection that's currently hidden. Would it be possible for the appropriate expansion/collapse to happen immediately, while the page scrolls?

I know you can make the smooth scroll quicker or turn it off (although I haven't tried), but the next two steps would presumably still be sequential.

**Comment by tscanlin** [comment]
Having it happen immediately would cause it to expand as it scrolls down the page as well and that would look weird because so many sections would expand/collapse so I'm afraid this isn't really easily possible. If you want to take a stab at implementing it be my guest, but it's not something I plan to attempt. Thanks for the suggestion though.
