### ISSUE TITLE
HTML in headlines is not working

### ISSUE THREAD

**Issue by sokai** [tscanlin/tocbot#14]
Hey!

Today I noticed that using `<sup>` in a headline the TOC entry is not correct/ignored. – Can you fix it, please?!

**Example:**
`<h3 id="app-current">„Test<sup><small><strong>16.1</strong></small></sup>“</h3>`
becomes
`<a class="toc-link node-name--H3 " href="#app-current" data-scroll="">„Test16.1“</a>`
in TOC.

Thanks and best regards! :-)

**Comment by tscanlin** [comment]
Yeah, right now tocbot only includes the textContent of the heading node. I can add the feature for it to be able to get the child nodes as well so that the html formatting passes through. However I don't want to break existing projects so I'm going to make it an option you can pass through when initializing.

What do you think about the name `includeHtml` for that option? The value passed to it would be a boolean. Let me know what you think and I'll make a PR with this change.

**Comment by sokai** [comment]
Hey @tscanlin ! Thanks for your fast and positive feedback!

I agree with your thoughts and will vote for the new `includeHtml`option. Nice to see that soon …

Best regards!

**Comment by tscanlin** [comment]
This should be fixed in:
https://github.com/tscanlin/tocbot/pull/15

Let me know what you think and I can merge it whenever.

**Comment by sokai** [comment]
Tanks @tscanlin ts, again! :-)

_Small_ question: How can I test your PR? (I never fiddled around with nmp etc. I only downloaded and used the release package … :-|)

**Comment by tscanlin** [comment]
Well you could clone it locally, checkout the branch from my PR and run the commands to build it. I generally don't improve compiled files in PRs because it makes for a big noisy diff.

But I'm about to go to sleep so I decided to just go ahead and merge the PR and publish on npm. You can download the latest release here: https://github.com/tscanlin/tocbot/releases

I'm going to consider this issue closed, but if you have any issues let me know and I can re-open it. Enjoy the rest of your weekend and thanks for the feature suggestion!

**Comment by sokai** [comment]
@tscanlin: Thanks for merging and releasing! :-)

Tested it and it works well! – Great job!

Sleep well ;-) and best regards!
