### ISSUE TITLE
Jquery version of tocbot ?

### ISSUE THREAD

**Issue by dbjpanda** [tscanlin/tocbot#142]
Hi, 
Thanks for this beautiful plugin. I was looking for a latest toc plugin to develop a Wordpress plugin. Though I can use this native Js plugin without any hesitation but Wordpress natively enqueue Jquery so why reinventing wheel in that case. So it would be great if a jquery version of the same can be provided as well.

**Comment by tscanlin** [comment]
Thanks. It's not reinventing the wheel, it simply uses native APIs because I prefer them over jquery's arbitrary and non-standard APIs. Its also more performant not to use jquery since that would mean there are more methods being called to accomplish the same things. Thanks for the suggestion but I won't be doing this.
