### ISSUE TITLE
Callback for changing toc labels

### ISSUE THREAD

**Issue by bahumbert** [tscanlin/tocbot#157]
Hey there!

First I would like to say this lib is truely awesome! I searched for this for a while but found nothing else really working for my needs.

I have a suggestion / request though. My headers are sometimes quite long, and since the toc has less space they sometimes takes like 6 lines or more. I don't really like that, and using a simple `text-overflow: ellipsis` is not really nice since I would like a little more than a single line with only a few words.

A really cheap example:
![image](https://user-images.githubusercontent.com/14981290/67983834-c88a3100-fc25-11e9-9fb8-f7aac47ef259.png)

Unfortunately for what I've found it's apparently impossible currently to do that with a pure CSS solution. There is a thing with `-webkit-box` and `-webkit-line-clamp` but as the name suggests it's non-standardized and may change in the future.. not really an option then. There's also some hacks but they needs both pseudo elements (`before` & `after`) and one is already used by tocbot.

If you have an idea I'm all ears! Otherwise, that leaves only the JS solution. That's why I'm creating this issue.

I'm not asking that you implement this because I guess that's a niche demand. Instead why not simply offering somekind of a callback, so that each time your lib "gets" a header we can do whatever we want with that and return the processed label so that the toc will display it? Maybe that could also be used to completly change the label for something more concise than the real (long) header  :thinking: .

What do you think?

**Comment by tscanlin** [comment]
Hey, I really like this idea, thanks for opening the issue! Also thanks for presenting some really good ideas to solve this as that is also very helpful.

1. Doing my own research it appears that the support for line-clamp is actually pretty decent.
https://caniuse.com/#feat=css-line-clamp
Everything but IE 11 which is only at 2% globally so I'd say thats a pretty decent option, it just means those users wouldn't see the nice ellipsis but the degradation doesn't seem to bad.

2. Then there's the css-tricks solution that is more cross browser compatible but also requires quite a bit of CSS. https://stackoverflow.com/questions/15909489/text-overflow-ellipsis-on-two-lines
But your right that way would only work if I added another wrapper element to the toc list items since I already use a pseudo element but that is also an option.

3. And then finally leaves the callback solution you had which I also like and may give flexibility for other functionality that I have not foreseen. This does have some JS overhead but should be very minimal.

I'm fine with any of these solutions really. But probably leaning towards 1 or 3 since they would require the fewest lines of code and seem the simplest.

What do you think, do you have a preference? Also are you interested in making a PR?

**Comment by tscanlin** [comment]
Oh, I also like this way too:
https://css-tricks.com/line-clampin/#article-header-id-1

**Comment by bahumbert** [comment]
Well, I admit I'm also balanced between the first and the third :smile: 

However the first one has the major drawback of being non-standardized, so there's a probability some browsers will drop that someday or will make changes that will break the current implementation. I guess that's not something we want for a website on production..

However the specs there https://drafts.csswg.org/css-overflow-3/#webkit-line-clamp mentions that future changes to this implementation should keep compatibility (if I understand correctly). Indeed it's quite weird that all major browsers currently support this, that may be a good sign...

Still, apparently there's other problems with some "details", like for Chinese for example : https://medium.com/mofed/css-line-clamp-the-good-the-bad-and-the-straight-up-broken-865413f16e5 (though I'm not sure if this post is still up to date, but it's linked by the specs as you can see). And there's also the fact if someone really wants to use this he can, by simply applying that CSS without modyfing the lib.


All-in-all I still think it's a bit risky to go for that for now, so I've a little preference for the third solution. As you said it leaves more flexibility to do many other things so that's a plus. 

The fourth you mentioned (the fade out way) also seems to be implementable by a user without the need of changing the lib.

So we go for the third solution? Sure I'd be glad to help with a PR! I'll try to take the time in the following week if you want :+1: .

**Comment by tscanlin** [comment]
Cool, yeah if you want to work on that next week I’d be happy to review it once it’s ready. Thanks for the thoughtful discussion!

**Comment by bahumbert** [comment]
I actually had more time than planned this weekend, here it is: #158!
