### ISSUE TITLE
TOC node clicked is not TOC node marked as selected

### ISSUE THREAD

**Issue by odrotbohm** [tscanlin/tocbot#207]
I see Tocbot behaving in a totally erratic way. After selecting TOC nodes, a completely different one is marked as selected. Also, not all TOC nodes are expanded. Checkout [this page](https://quarano.de/internal-dev/api/docs/index.html). Go to "10. Business modules" and note how not that node is selected but "Spring profiles". Also, the subheadings of "Business modules" are not expanded which I suspect is a consequence of the node not being selected properly. I've tried what's suggested in #173 but without success. The same behavior can be used on a [similarly structured site](https://docs.spring.io/spring-hateoas/docs/1.2.1/reference/html/).

I have [other Asciidoctor generated sites](https://st.inf.tu-dresden.de/SalesPoint/salespoint-reference.html) that work just fine. I suspect something wrong with the HTML structure in the problematic sites in the first place.

**Comment by odrotbohm** [comment]
A bit more investigating. The broken pages seem to be broken in Chrome based browsers only. Safari and Firefox look good. So something in the broken pages' HTML seems to upset Chrome 😕.

**Comment by tscanlin** [comment]
hmm this is really quite peculiar.. Glad you figured out that its a chrome only thing!
I saw you had some fancy new css like
```
    content-visibility: auto;
    contain-intrinsic-size: 1px 2000px;
```
My thought is that maybe the new content visibility stuff is changing the way the DOM is being rendered so that tocbot is not able to calculate offsets properly. I know these pages are extra long too so maybe chrome doesn't like that, not too sure. Hope that helps, let me know what you find out.

**Comment by bclozel** [comment]
@tscanlin I think you're right, this is probably linked with that optimization. This is the textbook limitation with that optimization: 1) don't apply that directive on nodes that might layout out of the flow or interact with each other, 2) don't do that if you do offset calculations.

I wasn't aware tocbot was working with offsets, so that's our mistake. Sorry for that, and thanks for pointing the issue so quickly!

**Comment by tscanlin** [comment]
Happy to help!
