### ISSUE TITLE
Changing hash when scrolling

### ISSUE THREAD

**Issue by smeedijzer-internet** [tscanlin/tocbot#208]
Hi,

What do you think about the idea to change the hash of the url when scrolling?

**Comment by tscanlin** [comment]
Hello, thanks for sharing this idea. I think that this is a very interesting concept. However, I don't think this should be a concern of tocbot since it is much more focused on the toc generation and UI / animation.

I think this could be its own library or something controlled by developers since you could have/want this without having a toc ui. Here is a script I found after a quick google search which appears to do just that. https://gist.github.com/JoeSz/48743c0d898bf6e6735064cc3d564a9d#file-change-url-while-scrolling-html-L52

Hope that helps.

**Comment by smeedijzer-internet** [comment]
Thanks for helping. Maybe the hash change shouldn't be part of Tocbot indeed. But is there a way to get the active item with the event: scrollEndCallback?(or an other way) Then I can add the hash change to this event. Plus I think a build-in way to get the active item could be handy for other cases.

```
scrollEndCallback: function (e) {
     window.location.hash = // activeItem ?
 },
```

**Comment by tscanlin** [comment]
I don't think that callback will work for what you want since it only fires on the animated scroll end once the user has clicked an item in the TOC, it doesn't fire for every scroll event. But to get the active item you should be able to do something like this: `document.querySelector(tocbot.options.activeLinkClass)` in your scroll listener. I'd be open to adding a convenience method for this in the future if this solves your use case and if other people ask for this functionality. Hopefully that helps.
