### ISSUE TITLE
Allow specifying where `top` should be calculated from

### ISSUE THREAD

**Issue by twe4ked** [tscanlin/tocbot#21]
Hi,

I'm working on a project where the page content is inside a `position: fixed;` element with `overflow: scroll` set. This seems to break the way `top` is calculated.

I believe the fix would be to fall back to `scrollTop` of the content container. Perhaps this could use the existing `contentSelector` option to find the element?

Relevant line:

https://github.com/tscanlin/tocbot/blob/cd01b21d6e7b339e313f9cf31772b852f053491b/src/js/build-html.js#L133

I don't do much front end dev so I'm not sure if this would be the best way. Would you accept a patch like that or is there another way you would tackle it?

Cheers

**Comment by tscanlin** [comment]
@twe4ked thanks for opening this issue. I figured someone might want this functionality eventually and I am open to adding it. Also, nice work finding the right code that will need to change.

Does the layout need to have a scrolling container rather than making the whole document scroll? One nice thing about having the document scroll is if you scroll down, then click a link, and then click back. Your scroll position should resume where you left off. Just thought I'd ask.

Also, are you using npm or something to use this library. I'm thinking I'll try to implement this feature and make a pre-release version that you can test, then once you've verified it works I can merge into master. Would that work for you?

Right now I'm thinking of calling this option `scrollingSelector` so that it is decoupled from the `contentSelector` option in case people have layouts that necessitate them being different elements. Also this would let me make the default value null to preserve the current behavior. Does that work for you?

**Comment by twe4ked** [comment]
> Does the layout need to have a scrolling container rather than making the whole document scroll? One nice thing about having the document scroll is if you scroll down, then click a link, and then click back. Your scroll position should resume where you left off. Just thought I'd ask.

Ah, that's a bummer I'd lose that functionality. I couldn't find another way to make the layout work without doing it this way.

> Also, are you using npm or something to use this library.

Yep!

> Right now I'm thinking of calling this option scrollingSelector [...]

`scrollingSelector` sounds perfect and `null` by default makes sense to me :)

I should say, I haven't been able to get it working hacking at the code locally so I could be wrong about this being my issue still. Although it might be my lack of JS build tools knowledge.

Thanks for getting back to me so quickly!

**Comment by twe4ked** [comment]
I've got a feeling the scroll event isn't firing either.

**Comment by tscanlin** [comment]
Yep, you are right.

Do you have an example anywhere that I could easily check out? Maybe I can help better if I saw the layout.

Also, are you currently using the `positionFixedClass` option because it doesn't really work inside of a scrolling container.

**Comment by twe4ked** [comment]
I do, but it's a real mess at the moment (read: WIP commits etc.).

https://github.com/twe4ked/api-docs (don't judge me! :P)

I'm not using `positionFixedClass`.

**Comment by tscanlin** [comment]
Thanks for posting your example, that is very helpful. :)

You can definitely make your layout work without scrolling containers. I made a very similar layout for Optimizely's developer documentation, see here: https://developers.optimizely.com/x/solutions/javascript/reference/index.html

First, you should try to use position: absolute less, but basically you want to make the left sidebar `position: fixed;`, then make sure all of the elements fro html down to to `.wrap` are `height: 100%;` eg: `html, body, #root, .container, .content, .wrap { height: 100% }`

And then just use `margin-left: 220px` on .content or .wrap.

Try that and let me know if it works.

I had a WIP PR, but implementing the feature isn't as easy as expected.. :/

**Comment by twe4ked** [comment]
Haha, that's exactly what I was going for! I'll have another go at getting it working. The problem I was having was getting the background to extend down the whole page if there wasn't enough content which is why I decided to go with the scrolling element. I th

**Comment by tscanlin** [comment]
Totally! One css rule that might help is: `min-height: 100vh;` if you add that to the element containing your background image it will insure that the minimum height is always 100% of the viewport (window) height even if there isn't enough content. Hope that helps!

**Comment by twe4ked** [comment]
Thanks :)

It's funny, I saw that yesterday when I was looking for a way to do it and disregarded it thinking the viewport was the size of the browser window… That's solved my problem. Happy holidays!

**Comment by tscanlin** [comment]
Glad to hear that. Happy holidays to you too!
