### ISSUE TITLE
dynamically click the active element link

### ISSUE THREAD

**Issue by samjco** [tscanlin/tocbot#223]
Is there a way to use js to dynamically click the active link?
I've tried:

`$('a.toc-link.node-name--H1.is-active-link').click(); `

doesn't work...

**Comment by tscanlin** [comment]
Can you link to an example website please? That seems like it should work but it's difficult to tell..

**Comment by samjco** [comment]
Just tested it on your site...
![image](https://user-images.githubusercontent.com/3359062/106554183-7bf46c00-64e0-11eb-9ac7-7accc971199e.png)

**Comment by tscanlin** [comment]
Well it won't work on every website because not all websites include jQuery. Also, simulating a click on the currently active link would likely have no effect. You can use vanilla JS to simulate a click on the first element in the toc using this: `document.querySelector('a.toc-link').click()`

Hope that helps.
