### ISSUE TITLE
Styling Tocbot as Bootstrap Pill?

### ISSUE THREAD

**Issue by giorgio79** [tscanlin/tocbot#51]
Would it be easy? :)

http://getbootstrap.com/components/#nav-pills

**Comment by tscanlin** [comment]
Try the extraLinkClasses option

**Comment by giorgio79** [comment]
Thx that seemed to have worked except subheadings do not appear now in the toc :)
demo
http://proofreadbot.com/ui/tocbot-demo/

using
```
	tocbot.init({
		// Where to render the table of contents.
		tocSelector: '#pbot_report_toc',
		// Where to grab the headings to build the table of contents.
		contentSelector: '#pbot_report',
		// Which headings to grab inside of the contentSelector element.
		headingSelector: 'h2, h3,h4',
		// Main class to add to lists.
		listClass: 'nav nav-pills nav-stacked',
	});
```

**Comment by tscanlin** [comment]
I think they are showing up in the list, they just aren't being nested correctly because of interfering css. Try removing other interfering classes / css and just including tocbot's styles. It also isn't hard to add the styles yourself to make the items pill shaped. You could do it easily without bootstrap.

**Comment by giorgio79** [comment]
Thx a lot! :) Will try.
